# Generated by Django 5.2.9 on 2025-12-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertpayout',
            name='currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
    ]
