# Generated by Django 5.2.9 on 2025-12-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kairos', max_length=100)),
                ('tagline', models.CharField(default="don't guess. know", max_length=200)),
                ('contact_email', models.EmailField(default='support@kairos.example.com', max_length=254)),
                ('support_email', models.EmailField(default='support@kairos.example.com', max_length=254)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('terms_version', models.CharField(default='1.0', max_length=20)),
                ('privacy_policy_version', models.CharField(default='1.0', max_length=20)),
                ('acceptable_use_version', models.CharField(default='1.0', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
                'db_table': 'core_site_settings',
            },
        ),
    ]
