# Generated by Django 5.2.9 on 2025-12-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_status',
            field=models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Client approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='expert_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('vetted', 'Vetted'), ('active', 'Active'), ('rejected', 'Rejected')], default='applied', help_text='Expert approval status', max_length=20),
        ),
    ]
