# Generated by Django 5.2.9 on 2025-12-15 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes'), (90, '90 minutes')], default=60)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('problem_statement', models.TextField(help_text='Brief description of what you need help with')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('in_session', 'In session'), ('completed', 'Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='draft', max_length=20)),
                ('jitsi_room_id', models.CharField(blank=True, max_length=100)),
                ('external_meeting_link', models.URLField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by_expert', models.BooleanField(default=False)),
                ('completed_by_client', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_client', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='experts.expertprofile')),
            ],
            options={
                'db_table': 'consultations_booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='booking_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_deliverable', models.BooleanField(default=False, help_text='Is this a deliverable from the expert?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consultations.booking')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultations_booking_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('shared', 'Shared note'), ('expert_private', 'Expert private note')], default='shared', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_notes', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='consultations.booking')),
            ],
            options={
                'db_table': 'consultations_booking_note',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConciergeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Describe what you need help with')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timeline', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_requests', to=settings.AUTH_USER_MODEL)),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_concierge_requests', to=settings.AUTH_USER_MODEL)),
                ('matched_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='experts.expertprofile')),
                ('preferred_expertise', models.ManyToManyField(blank=True, related_name='concierge_requests', to='experts.expertisetag')),
            ],
            options={
                'db_table': 'consultations_concierge_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='concierge_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='consultations.conciergerequest'),
        ),
        migrations.CreateModel(
            name='ExpertClientRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('notes', models.TextField(blank=True, help_text='Private notes about this client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_client_rating', to='consultations.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_from_experts', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ratings', to='experts.expertprofile')),
            ],
            options={
                'db_table': 'consultations_expert_client_rating',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='consultations.booking')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultations_review',
                'ordering': ['-created_at'],
            },
        ),
    ]
