# Generated by Django 5.2.9 on 2025-12-16 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('experts', '0003_remove_expertprofile_rate_30_min_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_description',
            field=models.CharField(blank=True, help_text='Duration description e.g. 2 weeks', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='expert_payout',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expert payout amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='scope',
            field=models.TextField(blank=True, help_text='Scope of the engagement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('research', 'Research'), ('advisory', 'Advisory')], default='consultation', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Engagement price - set by admin', max_digits=10),
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('problem_description', models.TextField(help_text='Describe the challenge or problem you need help with')),
                ('engagement_type', models.CharField(choices=[('consultation', 'Consultation'), ('research', 'Research'), ('advisory', 'Advisory')], default='consultation', max_length=20)),
                ('timeline_urgency', models.CharField(choices=[('low', 'Standard (2-4 weeks)'), ('medium', 'Priority (1-2 weeks)'), ('high', 'Urgent (within 1 week)'), ('critical', 'Critical (within 48 hours)')], default='low', max_length=20)),
                ('confidentiality_level', models.CharField(choices=[('standard', 'Standard'), ('elevated', 'Elevated'), ('strict', 'Strict NDA required')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('in_review', 'In review'), ('matched', 'Expert matched'), ('proposal_sent', 'Proposal sent'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Admin-set engagement price', max_digits=10, null=True)),
                ('expert_payout', models.DecimalField(blank=True, decimal_places=2, help_text='Expert payout amount', max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('internal_priority', models.IntegerField(default=0, help_text='Internal priority score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_requests', to=settings.AUTH_USER_MODEL)),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_client_requests', to=settings.AUTH_USER_MODEL)),
                ('matched_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_client_requests', to='experts.expertprofile')),
                ('preferred_expertise', models.ManyToManyField(blank=True, related_name='client_requests', to='experts.expertisetag')),
            ],
            options={
                'db_table': 'consultations_client_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='client_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='consultations.clientrequest'),
        ),
    ]
