# Generated by Django 5.2.9 on 2025-12-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_remove_booking_duration_booking_duration_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Invoice billing email', max_length=254),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='organisation_name',
            field=models.CharField(blank=True, help_text='Organisation for invoicing', max_length=200),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase order number', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
    ]
