# Generated by Django 5.2.9 on 2025-12-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_clientrequest_billing_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='brief_document',
            field=models.FileField(blank=True, help_text='Upload a brief or proposal (PDF, DOCX)', null=True, upload_to='client_briefs/'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='budget_range',
            field=models.CharField(blank=True, help_text='Optional budget range', max_length=100),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='POPIA consent for data processing'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=30),
        ),
    ]
