# Generated by Django 5.2.9 on 2025-12-16 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('excerpt', models.TextField(help_text='Brief summary for listing pages', max_length=500)),
                ('content', models.TextField(help_text='Main content (HTML allowed)')),
                ('author_name', models.CharField(default='Kairos Team', max_length=200)),
                ('reading_time_minutes', models.PositiveIntegerField(default=5, help_text='Estimated reading time')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
                'db_table': 'blog_post',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
