# Generated by Django 5.2.9 on 2025-12-15 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tag_type', models.CharField(choices=[('discipline', 'Discipline'), ('industry', 'Industry')], default='discipline', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'experts_expertise_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, help_text='One sentence describing your expertise', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Detailed biography')),
                ('pronouns', models.CharField(blank=True, max_length=50)),
                ('affiliation', models.CharField(blank=True, help_text='Current organisation or institution', max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('orcid_id', models.CharField(blank=True, help_text='ORCID identifier', max_length=50)),
                ('rate_30_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_60_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_90_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('project_work_available', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending verification'), ('verified', 'Verified'), ('needs_changes', 'Needs changes'), ('rejected', 'Rejected')], default='incomplete', max_length=20)),
                ('verification_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verification_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Internal notes from admin review')),
                ('is_publicly_listed', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_consultations', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise_tags', models.ManyToManyField(blank=True, related_name='experts', to='experts.expertisetag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
                ('verification_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_experts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experts_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotableProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notable_projects', to='experts.expertprofile')),
            ],
            options={
                'db_table': 'experts_notable_project',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('patent_number', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='experts.expertprofile')),
            ],
            options={
                'db_table': 'experts_patent',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='experts.expertprofile')),
            ],
            options={
                'db_table': 'experts_publication',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('degree', 'Degree certificate'), ('employment', 'Employment letter'), ('other', 'Other documentation')], max_length=20)),
                ('file', models.FileField(upload_to='verification_documents/')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='experts.expertprofile')),
            ],
            options={
                'db_table': 'experts_verification_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
