# Generated by Django 5.2.9 on 2025-12-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_expertapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='rate_30_min',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='rate_60_min',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='rate_90_min',
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='expert_payout_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expert payout rate - expert only', max_digits=10),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='internal_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Internal pricing - admin only', max_digits=10),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured on homepage'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('semi_private', 'Semi-private'), ('private', 'Private')], default='semi_private', help_text='Controls profile visibility', max_length=20),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='sector_expertise',
            field=models.TextField(blank=True, help_text='Industry sectors of expertise'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='senior_roles',
            field=models.TextField(blank=True, help_text='Senior positions held'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='years_experience',
            field=models.IntegerField(default=0, help_text='Years of professional experience'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='verification_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('vetted', 'Vetted'), ('active', 'Active'), ('needs_changes', 'Needs changes'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
