# Generated by Django 5.2.9 on 2025-12-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_remove_expertprofile_rate_30_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='cv_file',
            field=models.FileField(blank=True, help_text='CV file (PDF or DOCX)', null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
    ]
