# Generated by Django 5.2.9 on 2025-12-17 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organisation_name', models.CharField(max_length=200)),
                ('billing_email', models.EmailField(blank=True, help_text='Required for invoicing', max_length=254)),
                ('phone', models.CharField(default='+27', help_text='Contact phone number', max_length=30)),
                ('engagement_type', models.CharField(choices=[('consultation', 'Consultation'), ('research', 'Research'), ('advisory', 'Advisory')], default='consultation', max_length=20)),
                ('urgency', models.CharField(choices=[('standard', 'Standard (2-4 weeks)'), ('urgent', 'Urgent (within 1 week)')], default='standard', max_length=20)),
                ('brief', models.TextField(help_text='Describe the challenge or problem you need help with')),
                ('attachment', models.FileField(blank=True, help_text='Upload a brief document (PDF/DOCX)', null=True, upload_to='engagement_briefs/')),
                ('confidentiality_level', models.CharField(choices=[('standard', 'Standard'), ('restricted', 'Restricted')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In review'), ('shortlisted', 'Experts shortlisted'), ('proposal_sent', 'Proposal sent'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('awaiting_client', 'Awaiting client confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='submitted', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'engagements_client_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('awaiting_client', 'Awaiting client confirmation'), ('completed', 'Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('meeting_mode', models.CharField(choices=[('platform', 'Platform'), ('admin_facilitated', 'Admin facilitated')], default='platform', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='External meeting link if applicable')),
                ('shared_notes', models.TextField(blank=True, help_text='Notes visible to both parties')),
                ('private_expert_notes', models.TextField(blank=True, help_text='Private notes for expert only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_engagements', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='engagements.clientrequest')),
            ],
            options={
                'db_table': 'engagements_engagement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('declined', 'Declined'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='proposed', max_length=20)),
                ('note_to_client', models.TextField(blank=True, help_text='Note visible to client')),
                ('internal_note', models.TextField(blank=True, help_text='Internal admin note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_proposals', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_matches', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_matches', to='engagements.clientrequest')),
            ],
            options={
                'verbose_name': 'Expert match',
                'verbose_name_plural': 'Expert matches',
                'db_table': 'engagements_expert_match',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('request_submitted', 'Request submitted'), ('request_in_review', 'Request in review'), ('expert_shortlisted', 'Expert shortlisted'), ('expert_proposed', 'Expert proposed'), ('expert_accepted', 'Expert accepted'), ('expert_declined', 'Expert declined'), ('proposal_sent', 'Proposal sent'), ('client_confirmed', 'Client confirmed'), ('engagement_scheduled', 'Engagement scheduled'), ('engagement_started', 'Engagement started'), ('engagement_completed', 'Engagement completed'), ('request_cancelled', 'Request cancelled'), ('request_expired', 'Request expired'), ('note_added', 'Note added'), ('status_changed', 'Status changed')], max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='engagements.clientrequest')),
            ],
            options={
                'verbose_name': 'Progress event',
                'verbose_name_plural': 'Progress events',
                'db_table': 'engagements_progress_event',
                'ordering': ['created_at'],
            },
        ),
    ]
